apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: pacman
  labels:
    app: pacman
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
