apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: pacman
  labels:
    app: pacman
spec:
  replicas: {{ .Values.pacman.replicas }}
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      serviceAccountName: pacman
      containers:
        - name: pacman-app
          image: {{ .Values.pacman.image }}
          env:
            - name: MONGO_SERVICE_HOST
              value: mongodb
            - name: MONGO_AUTH_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mongodb-users-secret
            - name: MONGO_AUTH_PWD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mongodb-users-secret
            - name: MONGO_DATABASE
              value: pacman
            - name: MY_MONGO_PORT
              value: "27017"
            - name: MONGO_USE_SSL
              value: "false"
            - name: MONGO_VALIDATE_SSL
              value: "false"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              protocol: TCP
