apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
  namespace: pacman
type: Opaque
data:
  database-admin-password: {{ .Values.secrets.databaseAdminPassword | quote }}
  database-name: {{ .Values.secrets.databaseName | quote }}
  database-password: {{ .Values.secrets.databasePassword | quote }}
  database-user: {{ .Values.secrets.databaseUser | quote }}
  keyfile-value: {{ .Values.secrets.keyfileValue | quote }}
